name: jack

on:
  push:
    branches:
      - main
jobs:
  build:

    env:
      PY_COLORS: "1"
      GLOBAL_PROXY: ${{ secrets.GLOBAL_PROXY }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: demo 
      run:  python werker.py 

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: "0"
